# Generated by Django 4.2.23 on 2025-06-17 01:53

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=utils.utils.generar_nombre_imagen_share)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('viajes', 'Viajes'), ('comida', 'Comida'), ('arte', 'Arte'), ('musica', 'Música'), ('peliculas', 'Películas'), ('videojuegos', 'Videojuegos'), ('amor', 'Amor'), ('amistad', 'Amistad'), ('comedia', 'Comedia'), ('libros', 'Libros'), ('terror', 'Terror'), ('redes_sociales', 'Redes Sociales'), ('vida_social', 'Vida Social'), ('deportes', 'Deportes'), ('tecnologia', 'Tecnología'), ('tendencias', 'Tendencias'), ('salud', 'Salud'), ('educacion', 'Educación'), ('negocios', 'Negocios')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
